-- Road Accident & Collision Management System

CREATE DATABASE IF NOT EXISTS road_accident_db;
USE road_accident_db;

-- Drop existing tables in reverse dependency order to prevent FK conflicts
DROP TABLE IF EXISTS COLLISION_AUDIT;
DROP TABLE IF EXISTS CASUALTY;
DROP TABLE IF EXISTS COLLISION_FACTOR;
DROP TABLE IF EXISTS CONTRIBUTING_FACTOR;
DROP TABLE IF EXISTS COLLISION_VEHICLE;
DROP TABLE IF EXISTS VEHICLE_TYPE;
DROP TABLE IF EXISTS COLLISION;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS ZIP_CODE;
DROP TABLE IF EXISTS BOROUGH;

-- 1. Table: BOROUGH
CREATE TABLE BOROUGH (
    BOROUGH VARCHAR(20) NOT NULL,
    CONSTRAINT PK_BOROUGH PRIMARY KEY (BOROUGH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Table: ZIP_CODE
CREATE TABLE ZIP_CODE (
    ZIP_CODE CHAR(6) NOT NULL,
    BOROUGH VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ZIP_CODE PRIMARY KEY (ZIP_CODE),
    CONSTRAINT FK_ZIP_BOROUGH FOREIGN KEY (BOROUGH) 
        REFERENCES BOROUGH (BOROUGH) 
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 3. Table: LOCATION
CREATE TABLE LOCATION (
    LATITUDE DECIMAL(10, 7) NOT NULL,
    LONGITUDE DECIMAL(10, 7) NOT NULL,
    ON_STREET_NAME VARCHAR(150) NULL,
    CROSS_STREET_NAME VARCHAR(150) NULL,
    OFF_STREET_NAME VARCHAR(150) NULL,
    ZIP_CODE CHAR(6) NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (LATITUDE, LONGITUDE),
    CONSTRAINT FK_LOCATION_ZIP FOREIGN KEY (ZIP_CODE) 
        REFERENCES ZIP_CODE (ZIP_CODE) 
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- 4. Table: COLLISION
CREATE TABLE COLLISION (
    COLLISION_ID INT NOT NULL,
    ACCIDENT_DATE DATE NOT NULL,
    ACCIDENT_TIME TIME NOT NULL,
    LATITUDE DECIMAL(10, 7) NOT NULL,
    LONGITUDE DECIMAL(10, 7) NOT NULL,
    CONSTRAINT PK_COLLISION PRIMARY KEY (COLLISION_ID),
    CONSTRAINT FK_COLLISION_LOCATION FOREIGN KEY (LATITUDE, LONGITUDE) 
        REFERENCES LOCATION (LATITUDE, LONGITUDE) 
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Table: VEHICLE_TYPE
CREATE TABLE VEHICLE_TYPE (
    VEHICLE_TYPE_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_VEHICLE_TYPE PRIMARY KEY (VEHICLE_TYPE_CODE),
    CONSTRAINT CHK_VEHICLE_TYPE_CODE CHECK (
        VEHICLE_TYPE_CODE IN (
            'ATV', 'Bicycle', 'Car/SUV', 'Ebike', 
            'Escooter', 'Truck/Bus', 'Motorcycle', 'Other'
        )
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Table: COLLISION_VEHICLE (M:N Associative Entity)
CREATE TABLE COLLISION_VEHICLE (
    COLLISION_ID INT NOT NULL,
    VEHICLE_TYPE_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_COLLISION_VEHICLE PRIMARY KEY (COLLISION_ID, VEHICLE_TYPE_CODE),
    CONSTRAINT FK_CV_COLLISION FOREIGN KEY (COLLISION_ID) 
        REFERENCES COLLISION (COLLISION_ID) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CV_VEHICLE_TYPE FOREIGN KEY (VEHICLE_TYPE_CODE) 
        REFERENCES VEHICLE_TYPE (VEHICLE_TYPE_CODE) 
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Table: CONTRIBUTING_FACTOR
CREATE TABLE CONTRIBUTING_FACTOR (
    CONTRIBUTING_FACTOR_VEHICLE VARCHAR(150) NOT NULL,
    CONSTRAINT PK_CONTRIBUTING_FACTOR PRIMARY KEY (CONTRIBUTING_FACTOR_VEHICLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Table: COLLISION_FACTOR (M:N Associative Entity)
CREATE TABLE COLLISION_FACTOR (
    COLLISION_ID INT NOT NULL,
    CONTRIBUTING_FACTOR_VEHICLE VARCHAR(150) NOT NULL,
    CONSTRAINT PK_COLLISION_FACTOR PRIMARY KEY (COLLISION_ID, CONTRIBUTING_FACTOR_VEHICLE),
    CONSTRAINT FK_CF_COLLISION FOREIGN KEY (COLLISION_ID) 
        REFERENCES COLLISION (COLLISION_ID) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CF_FACTOR FOREIGN KEY (CONTRIBUTING_FACTOR_VEHICLE) 
        REFERENCES CONTRIBUTING_FACTOR (CONTRIBUTING_FACTOR_VEHICLE) 
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. Table: CASUALTY (1:1 Entity linked to COLLISION)
CREATE TABLE CASUALTY (
    COLLISION_ID INT NOT NULL,
    NUMBER_OF_PERSONS_INJURED INT NOT NULL DEFAULT 0,
    NUMBER_OF_PERSONS_KILLED INT NOT NULL DEFAULT 0,
    NUMBER_OF_PEDESTRIANS_INJURED INT NOT NULL DEFAULT 0,
    NUMBER_OF_PEDESTRIANS_KILLED INT NOT NULL DEFAULT 0,
    NUMBER_OF_CYCLIST_INJURED INT NOT NULL DEFAULT 0,
    NUMBER_OF_CYCLIST_KILLED INT NOT NULL DEFAULT 0,
    NUMBER_OF_MOTORIST_INJURED INT NOT NULL DEFAULT 0,
    NUMBER_OF_MOTORIST_KILLED INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_CASUALTY PRIMARY KEY (COLLISION_ID),
    CONSTRAINT FK_CASUALTY_COLLISION FOREIGN KEY (COLLISION_ID) 
        REFERENCES COLLISION (COLLISION_ID) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CHK_PERSONS_INJURED CHECK (NUMBER_OF_PERSONS_INJURED >= 0),
    CONSTRAINT CHK_PERSONS_KILLED CHECK (NUMBER_OF_PERSONS_KILLED >= 0),
    CONSTRAINT CHK_PED_INJURED CHECK (NUMBER_OF_PEDESTRIANS_INJURED >= 0),
    CONSTRAINT CHK_PED_KILLED CHECK (NUMBER_OF_PEDESTRIANS_KILLED >= 0),
    CONSTRAINT CHK_CYC_INJURED CHECK (NUMBER_OF_CYCLIST_INJURED >= 0),
    CONSTRAINT CHK_CYC_KILLED CHECK (NUMBER_OF_CYCLIST_KILLED >= 0),
    CONSTRAINT CHK_MOT_INJURED CHECK (NUMBER_OF_MOTORIST_INJURED >= 0),
    CONSTRAINT CHK_MOT_KILLED CHECK (NUMBER_OF_MOTORIST_KILLED >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. Table: COLLISION_AUDIT (Audit Trail for Dynamic Auditing Trigger)
CREATE TABLE COLLISION_AUDIT (
    AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
    COLLISION_ID INT NOT NULL,
    ACTION_TYPE VARCHAR(20) NOT NULL,
    OLD_ACCIDENT_DATE DATE NULL,
    NEW_ACCIDENT_DATE DATE NULL,
    CHANGE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    PERFORMED_BY VARCHAR(100) DEFAULT (CURRENT_USER())
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
